### ISSUE TITLE
shared_preferences ^2.0.11

### ISSUE THREAD

**Issue by pburel** [Crash-Catch/CrashCatchLib-Flutter#2]
Because crashcatchlib_flutter >=2.0.0 depends on shared_preferences ^0.5.4+3 and crashcatchlib_flutter <2.0.0 depends on shared_preferences ^0.4.2, every version of crashcatchlib_flutter requires shared_preferences ^0.4.2 or ^0.5.4+3.
So,  ...
could you upgrade ? shared_preferences ^2.0.11

**Comment by boardy** [comment]
Hi, 

Yea no problem. I'll take a look at that today and see if I can get a new release out over the weekend to resolve that.

I'll let you know when its available.

Thanks
Chris Board

**Comment by boardy** [comment]
Hi again. I've published version 2.0.1 which updates shared_preferences to 2.0.13 which is the latest version so hopefully that should do the trick. 

Please let me know how you get on.

**Comment by boardy** [comment]
Hi,

Just to let you know I've just published version 2.1.1 which includes the changes above, but I also noticed the package was being treated as a legacy package as it didn't have null safety. This has now been fixed and it also includes added support for Windows Desktop and Web as well as Android and iOS.

**Comment by boardy** [comment]
No further response so closing. Please reply, or open a new issue if the problem still exists
